# Vitenskapsfilosofi

Jeg har valgt oppgave 1 og 2. Jeg skal ta for meg Humes argumentasjon mot induksjon, samt se på om det er mulig å unngå hans konklusjon. Videre skal jeg gi en kort beskrivelse og forklaring av falsifikasjonisme. Til slutt vil jeg presenter ett problem med denne teorien, og se på om dette problemet kan løses?

Hume (1711--1776) var en empirist. Han mente at kunnskap skal ha opphav i erfaring gjennom sansene: syn, hørsel, berøring, lukt og smak. Hume mente at alle forestillinger bare er en samling av inntrykk. Han var en av de første til å kritisere induksjon. Induksjon er tankeprosess der vi drar slutninger fra minner og erfaringer fra fortiden. Hume var spesielt opptatt av hvordan man kan finne argumenter for å generalisere kunnskap fra det man har observert til det uobserverte. Et eksempel på induksjon er ravneparadokset, som er en observasjonsbasert bekreftelse av ulike påstander: Ravn 1 er sort, ravn 2 er sort, ravn 3 er sort osv. Altså er alle ravner sorte [@hempel2000]. Hume gir oss generelle grunner til å tro at denne formen for slutning ikke har noe rasjonelt grunnlag. Humes poeng er at vi ikke engang kan si at premissene sannsynliggjør konklusjonen uten å anta at fremtiden vil ligne fortiden, og dette er en antagelse vi ikke kan begrunne.

Hume mente at ettersom fremtiden ikke er nåtiden har man ikke erfart det enda, og hvis man ikke har erfart det er det ikke sikker viten. Han setter det på spissen ved å hevde at selv om solen har stått opp hver eneste morgen hittil, kan man ikke vite sikkert at solen vil stå opp i morgen. F.eks. Solen har stått opp hver dag i hittil, derfor kommer den til å stå opp i morgen. På hvilket grunnlag kan vi si at dette er sant? Tidligere erfaring. Hvordan gir fortiden oss grunn til å mene og tro noe om fremtiden? Fremtiden vil være som fortiden, i morgen kommer til å ligne på i dag, altså solen vil stå opp i morgen også. Hvordan vet vi dette? Fordi det har alltid tidligere skjedd. Hele denne slutningen faller på seg selv i en sirkelargumentasjon. Induksjon er dermed ikke en logisk gyldig slutning. At fremtiden vil være som fortiden kan man se er en skjult antagelse ved å sjekke hva som skjer med argumentet hvis man gjør en annen antagelse. F.eks. «Fremtiden vil være helt forskjellig fra fortiden». Derfor er «Fremtiden vil være som fortiden» et skjult premiss.

Hume sier at vi ikke kan rasjonelt begrunne uniformitetsprinsippet (UP). Han mener mange ender opp med å tro, på kun av vane, og at alle årsaker dermed vil føre til like virkninger som vi har erfart i fortiden og nåtiden [@bøhn2015]. Her er en idé som i utgangspunktet ser ut til å være fornuftig: 1) UP har alltid vært sann tidligere, 2) UP er sann nå, 3) derfor vil UP være sann i fremtiden. Dette argumentet er altså sirkulært, og det finnes ikke noe ikke-sirkulært argument for UP. Hume mente videre at det ikke er noe rasjonell begrunnelse for UT, det kan ikke bevises gjennom logikk, og man kan ikke sjekke om det er sant. UP er altså bare noe man må anta uten begrunnelser. Humes argument blir da: 1) Hvert induktivt argument forutsetter UP, 2) UP har ingen rasjonal begrunnelse, 3) derfor har konklusjonen av alle induktive argumenter ingen rasjonal begrunnelse.

Selv om Hume har vist at vi ikke kan være sikre på at årsaker vil føre til lik virkning i nåtiden som vi har erfart i fortiden, er mange av våre overbevisninger rasjonelt begrunnet uten at vi er helt sikre på om de er sanne. I tillegg til at vi ikke kan være sikre på hva som kommer til å skje, gitt det som har skjedd tidligere, er Hume poeng at sannsynlighetspåstander også forutsetter uniformitetsprinsippet. For eksempel kan vi ikke utlede at solen vil stå opp i morgen fra prinsipper om fortiden, men sannsynligheten for at det skjer. Hvis man skal avvike fra UP, bør man ha en konkret grunn til å gjøre det. Og det har vi. Fysikkens og kjemiens lover har ikke endret seg, de er de samme i fortid og nåtid. Det vil derfor blant annet si at jern vil, også i fortiden, ruste til rødfarge i kontakt med oksygen, bølgemerker vil fortsatt dannes langs strendene og kull vil avsettes i sumpområder så lenge det finnes planter her.

Falsifiseringsprinsippet er knyttet til Karl Popper (1902--1994). Han mente at Humes induksjonsproblem ikke kunne løses, og at induktiv logikk er et mislykket prosjekt. Ifølge Popper er det å lete etter bekreftelser på hypoteser faktisk kjennetegn på pseudovitenskap. Han hevdet at verifikasjon ikke hadde noen rolle i vitenskap i det hele tatt, men at all vitenskap er nødt til å være falsifiserbar. Om teorien blir verifisert, som betyr bekreftes, eller falsifisert vil det ha påvirkning på teoriens validitet (gyldighet). Selv om teorien verifiseres, er det ifølge Popper enda ikke gitt at teorien stemmer.

Avgrensningsproblemet til Popper var å skille vitenskap fra ikke-vitenskap. Ved å si at S er en vitenskapelig påstand hvis og bare hvis S er falsifiserbar ble hans løsning på avgrensningsproblemet. Her kan vi ta ravneparadokset som et eksempel igjen. Påstanden om at alle ravner er svarte [@hempel2000]. Denne påstanden kan aldri verifiseres, fordi da må vi vite at alle ravner, i hele verden, til enhver tid har vært svarte. Derimot kan den falsifiseres ved å se én ravn med en annen farge enn svart. Man må merke seg at et utsagn kan være falsifiserbart uten å være usant, for eksempel kan et objekt være vannløselig uten faktisk oppløsning. Videre må man se opp for følgene feil som blander sammen folk og påstander. Selv om folk som tror teori T er uvillige til å gi opp sin tro uansett hva bevisene er, er ikke teori T falsifiserbar. Tenk her på falsifiserbare uttalelse som «Jorden er flat» eller «Månen er helt rund». Det faktum at det er flat jord eller rund måne viser ikke at teorien ikke er falsifiserbar. Man må også merke seg at det er flere grader av falsifisering. En teori eller uttalelse er mer falsifiserbar enn en annen hvis den innebærer mer presise eller flere prediksjoner.

Gjennom falsifikasjon av en teori vil man aldri kunne gi den status som endelig og korrekt, da den plutselig en dag kanskje vil vise seg å være falsifisert ved en etterprøving av teorien, altså være feil. Selv om en teori er utprøvd uendelig mange ganger, og aldri blitt falsifisert, kan en ikke si at den er verifisert, da dette ikke er logisk gyldig å si. Man må leve med at de teoriene vi har er gjenstand for forbedring og utbytting. I den forstand kan man aldri oppnå sikker viten. Poppers svar på dette var at slike teorier er «korroborert» selv om de ikke er bekreftet. Med bekreftelse mente han at det er empirisk evidens som viser at teorien er sann og med korroborasjon mente han at teorien har overlevd mange tidligere tester.

Avslutningsvis kan man likevel si at det er noen mangler og feilslutninger i både Humes og Poppers teorier som gjør at de bør ses som rettesnorer heller enn absolutte sannheter [@malnes2018]. Induksjon kan være nyttig i det daglige liv på tross av dens mangler på rent logisk grunnlag. Falsifisering i praksis vil si at en sterk teori kan komme til å bli forkastet til fordel for en svakere teori. Det bør være mulig å tilbakevise teorier i tidlig stadium, ettersom alle gode studier utvikles over lang tid. Med studier følger det også noen tilleggsantagelser, som for eksempel et måleinstrument som ikke stemmer. Feil ved måleinstrumentet kan da føre til at en hypotese, på feil grunnlag, kan bli forkastet. Men når det kommer til vitenskapen er det klart at falsifikasjon virkelig har noe for seg fremfor verifikasjon.
